name: bolsista_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  webview_flutter: ^4.9.0  
  file_picker: ^8.1.2
  provider: ^6.0.5
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  mime: ^1.0.6
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1
flutter:
  uses-material-design: true
  fonts:
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Light.ttf
  assets:
     - assets/images/logo_rede_campo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

